Add more stats + optimize
MaJerle/lwmem pull request #5
Opened 2022-03-14 17:15 UTC by upbeat27

Added more stats, and a function for retrieving the stats as brought up in #4 .
In the process of looking at the code, I saw an opportunity for optimization by removing many instance checks, to see if the default should be used. The instance won't change beyond the initial call, so it only needs to be done once.
Duplicating `mem_available_bytes` for the stats is not ideal, but the alternatives seemed even less so.

2022-03-14 17:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MaJerle/lwmem?pullRequest=5) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MaJerle/lwmem?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MaJerle/lwmem?pullRequest=5) it.</sub>

2022-03-14 17:48 UTC, MaJerle requested changes

2022-03-14 17:48 UTC, MaJerle commented on lwmem/src/include/lwmem/lwmem.h
> +#endif
Please add comment indicating to which #if it corresponds.

2022-03-14 17:48 UTC, MaJerle commented on lwmem/src/lwmem/lwmem.c
> +        for ((in_pp) = NULL, (in_p) = &(in_lw->start_block);  \
Since this is a macro, it should be done in a way `&((in_lw)->start_block)` instead

2022-03-14 17:48 UTC, MaJerle commented on lwmem/src/lwmem/lwmem.c
> +#define LWMEM_PROTECT(lw)         lwmem_sys_mutex_wait(&(lw->mutex))
Needs brackets for lw var `(lw)`

2022-03-14 17:48 UTC, MaJerle commented on lwmem/src/lwmem/lwmem.c
> +    } while (0)
macro parameters should be in brackets, `(lw)`

2022-03-14 17:48 UTC, MaJerle commented on lwmem/src/lwmem/lwmem.c
> +    lw = LWMEM_GET_LW(lw);
Initialization variables first, then assignment operator. Please move this after

2022-03-15 06:34 UTC, MaJerle approved these changes

2022-03-15 06:34 UTC, merged

2022-03-18 18:25 UTC, MaJerle commented
Unexpected too many bugs in the lib - have to fix them

2022-03-18 18:27 UTC, upbeat27 commented
> Unexpected too many bugs in the lib - have to fix them

As a result of this pull request?
What are they?
I am using it with multiple instances, with multiple regions and it has been solid so far.

2022-03-18 19:10 UTC, MaJerle commented
> > Unexpected too many bugs in the lib - have to fix them
> 
> As a result of this pull request? What are they? I am using it with multiple instances, with multiple regions and it has been solid so far.

Try to disable stats feature for test :)

2022-03-18 19:12 UTC, upbeat27 commented
Ah, I see. I forgot to check with stats disabled, as I would likely never do so.
Glad it is fixed though.